#ifndef    BLOCK_MENU_HH
# define   BLOCK_MENU_HH

# include <memory>
# include "Menu.hh"
# include "../world/Tiles.hh"

namespace new_frontiers {

  class BlockMenu: public Menu {
    public:

      /**
       * @brief - Create a new block menu allowing to interact
       *          (typically by creating or removing) blocks in
       *          the world. Upon clicking on this menu a new
       *          action to register or remove a block will be
       *          created.
       * @param pos - the position of the menu in the parent.
       * @param size - the dimensions of the menu.
       * @param name - the name of this menu.
       * @param type - the type of action attached to this menu.
       *               We mostly support `Creation` or `Deletion`
       *               here so an error will be raised of the
       *               type is not one of those.
       * @param block - the block attached to this menu. It will
       *                be associated to any action generated by
       *                this menu.
       * @param id - the variant of the block (default is `0`).
       * @param parent - the parent menu for this element. Specify
       *                 `null` in case the menu is the root of the
       *                 subsystem.
       */
      BlockMenu(const olc::vi2d& pos,
                const olc::vf2d& size,
                const std::string& name,
                const action::Type& type,
                const tiles::Block& block,
                int id = 0,
                Menu* parent = nullptr);

      /**
       * @brief - Desctruction of the object.
       */
      ~BlockMenu();

    protected:

      /**
       * @brief - Interface method allowing inheriting classes
       *          to perform the creation of their own actions
       *          whenver a click is detected on this menu.
       *          For now this method is only triggered when a
       *          click witht he left mouse button is detected.
       *          The default implementation does nothing.
       * @param actions - output vector to register actions if
       *                  needed.
       */
      virtual
      void
      onClick(std::vector<ActionShPtr>& actions) const;

    private:

      /**
       * @brief - The tile representing the block attached to
       *          this menu. Any action will concern this kind
       *          of block.
       */
      tiles::Block m_block;

      /**
       * @brief - The variant for the block attached to this
       *          menu.
       */
      int m_bVariant;

      /**
       * @brief - The type of action associated with this menu.
       *          Should be on of `Creation` or `Deletion` which
       *          correspond to either spawning or deleting a
       *          block from the world.
       */
      action::Type m_type;
  };

}

# include "BlockMenu.hxx"

#endif    /* BLOCK_MENU_HH */
